"""
Copyright Export Package Builder — Omni Veil Authorship Support Infrastructure

Assembles a ZIP archive containing all provenance and authorship documentation
for a given asset. The package is the portable, submittable record of creative
provenance documentation.

REQUIRED LEGAL DISCLAIMER appears in every file in the package.
"""

import io
import json
import os
import zipfile
from datetime import datetime, timezone
from typing import Optional

from app.services.copyright_report import generate_copyright_readiness_report
from app.services.copyright_readiness import LEGAL_DISCLAIMER


def build_export_package(asset) -> tuple[bytes, str]:
    """
    Build and return (zip_bytes, suggested_filename).

    The asset must have `.certificates`, `.provenance_events`, and
    `.contributors` loaded (lazy-loading is fine inside an open session).
    """
    report = generate_copyright_readiness_report(asset)
    now    = datetime.now(timezone.utc).isoformat()
    folder = f"{asset.omni_id}_copyright_export"

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        _write(zf, folder, "README.txt",                    _build_readme(asset, report, now))
        _write(zf, folder, "certificate.json",              _get_certificate(asset))
        _write(zf, folder, "provenance_manifest.json",      _get_manifest(asset))
        _write(zf, folder, "contributor_declarations.json", _build_contributor_declarations(report))
        _write(zf, folder, "workflow_analysis.json",        _build_workflow_analysis(report))
        _write(zf, folder, "timestamps.json",               _build_timestamps(report))
        _write(zf, folder, "audit_history.json",            _build_audit_history(asset, report))
        _write(zf, folder, "authorship_summary.json",       _build_authorship_summary(asset, report))

    buf.seek(0)
    return buf.read(), f"{asset.omni_id}_copyright_export.zip"


# ── File builders ──────────────────────────────────────────────────────────────

def _build_readme(asset, report: dict, now: str) -> str:
    cr  = report["copyright_readiness"]
    pc  = report["provenance_continuity"]
    own = report["ownership_declarations"]
    return f"""OMNI VEIL TRUST OS — COPYRIGHT EXPORT PACKAGE
{"=" * 60}

OMNI ID          : {asset.omni_id}
FILENAME         : {asset.filename}
GENERATED AT     : {now}
CERTIFICATE CLASS: {own.get("certificate_class", "standard") or "standard"}

TRUST SCORE              : {asset.trust_score}
CONTENT LABEL            : {asset.content_label}
COPYRIGHT READINESS SCORE: {cr.get("score") or "not yet scored"}
COPYRIGHT READINESS LABEL: {cr.get("label") or "—"}
PROVENANCE CONTINUITY    : {pc.get("score")} ({pc.get("label")})

PACKAGE CONTENTS
----------------
README.txt                    This file
certificate.json              Signed provenance certificate (latest)
provenance_manifest.json      Provenance manifest with integrity hash
contributor_declarations.json Formal authorship declarations per contributor
workflow_analysis.json        Workflow lineage and transformation chain
timestamps.json               Key lifecycle timestamps and event timeline
audit_history.json            Full immutable audit trail (all provenance events)
authorship_summary.json       Human authorship evidence and copyright readiness

LEGAL DISCLAIMER
----------------
{LEGAL_DISCLAIMER}

OWNERSHIP
---------
Copyright Owner : {own.get("copyright_owner") or asset.copyright_owner or "Unknown"}
License         : {own.get("license_type") or asset.license_type or "—"}

This package was generated by Omni Veil Trust OS.
Omni Veil provides provenance and authorship documentation infrastructure.
Final copyright determinations are made by the applicable copyright authority.
"""


def _get_certificate(asset) -> str:
    """Return the latest certificate JSON from the DB (authoritative source)."""
    certs = sorted(asset.certificates, key=lambda c: c.issued_at)
    if certs:
        try:
            # Re-parse and re-serialize to get consistent formatting
            data = json.loads(certs[-1].cert_json)
            data["_export_note"] = (
                "This is the latest certificate on record. "
                "Earlier versions exist in the audit history."
            )
            data["legal_disclaimer"] = LEGAL_DISCLAIMER
            return json.dumps(data, indent=2, default=str)
        except (json.JSONDecodeError, TypeError):
            return certs[-1].cert_json or "{}"

    # Fall back to file on disk if no DB record
    if asset.certificate_path and os.path.exists(asset.certificate_path):
        with open(asset.certificate_path) as fh:
            return fh.read()

    return json.dumps({"error": "No certificate found", "omni_id": asset.omni_id,
                       "legal_disclaimer": LEGAL_DISCLAIMER}, indent=2)


def _get_manifest(asset) -> str:
    """Return the provenance manifest, preferring disk (includes manifest_hash)."""
    if asset.manifest_path and os.path.exists(asset.manifest_path):
        with open(asset.manifest_path) as fh:
            raw = fh.read()
        # Append legal disclaimer to manifest data
        try:
            data = json.loads(raw)
            data["legal_disclaimer"] = LEGAL_DISCLAIMER
            return json.dumps(data, indent=2, default=str)
        except (json.JSONDecodeError, TypeError):
            return raw

    # Rebuild minimal manifest from DB fields
    return json.dumps({
        "manifest_version": "1.1",
        "omni_id": asset.omni_id,
        "filename": asset.filename,
        "sha256": asset.sha256,
        "blake3": asset.blake3,
        "phash": asset.phash,
        "trust_score": asset.trust_score,
        "content_label": asset.content_label,
        "copyright_owner": asset.copyright_owner,
        "license_type": asset.license_type,
        "created_at": asset.created_at.isoformat() if asset.created_at else None,
        "note": "Manifest file not found on disk; rebuilt from database record.",
        "legal_disclaimer": LEGAL_DISCLAIMER,
    }, indent=2, default=str)


def _build_contributor_declarations(report: dict) -> str:
    payload = {
        "declarations": report["contributor_declarations"],
        "human_contributors": report["human_contributors"],
        "ownership_declarations": report["ownership_declarations"],
        "legal_disclaimer": LEGAL_DISCLAIMER,
    }
    return json.dumps(payload, indent=2, default=str)


def _build_workflow_analysis(report: dict) -> str:
    payload = {
        "workflow_lineage": report["workflow_lineage"],
        "transformation_chain": report["transformation_chain"],
        "ai_tools": report["ai_tools"],
        "legal_disclaimer": LEGAL_DISCLAIMER,
    }
    return json.dumps(payload, indent=2, default=str)


def _build_timestamps(report: dict) -> str:
    payload = {
        **report["timestamps"],
        "legal_disclaimer": LEGAL_DISCLAIMER,
    }
    return json.dumps(payload, indent=2, default=str)


def _build_audit_history(asset, report: dict) -> str:
    """Full provenance event list — the immutable audit trail."""
    events = sorted(asset.provenance_events, key=lambda e: e.timestamp)
    payload = {
        "omni_id": asset.omni_id,
        "total_events": len(events),
        "audit_trail": [
            {
                "step": i + 1,
                "event_id": ev.event_id,
                "event_type": ev.event_type,
                "description": ev.description,
                "tool_used": ev.tool_used,
                "actor": ev.actor_name,
                "performed_by": ev.human_or_ai,
                "timestamp": ev.timestamp.isoformat() if ev.timestamp else None,
                "event_hash": ev.event_hash,
            }
            for i, ev in enumerate(events)
        ],
        "integrity_note": (
            "Each event_hash is a SHA-256 of the event's content at write time. "
            "Any mismatch indicates post-write tampering."
        ),
        "legal_disclaimer": LEGAL_DISCLAIMER,
    }
    return json.dumps(payload, indent=2, default=str)


def _build_authorship_summary(asset, report: dict) -> str:
    cr  = report["copyright_readiness"]
    payload = {
        "omni_id": asset.omni_id,
        "human_authorship_evidence": cr.get("human_authorship_evidence", {}),
        "confirmed_human_authorship_forms": cr.get("confirmed_human_authorship_forms", 0),
        "human_authorship_summary": asset.human_authorship_summary,
        "copyright_readiness_score": cr.get("score"),
        "copyright_readiness_label": cr.get("label"),
        "factors_supporting": cr.get("factors_supporting", []),
        "factors_limiting": cr.get("factors_limiting", []),
        "ai_tools": report["ai_tools"],
        "provenance_continuity": report["provenance_continuity"],
        "scoring_notes": {
            "trust_score": (
                "Measures provenance integrity — cryptographic chain, watermark, metadata."
            ),
            "copyright_readiness_score": (
                "Measures strength of documented human authorship evidence. "
                "Separate from trust_score."
            ),
            "provenance_continuity_score": (
                "Measures completeness of the provenance chain — events, hashes, manifest."
            ),
        },
        "legal_disclaimer": LEGAL_DISCLAIMER,
    }
    return json.dumps(payload, indent=2, default=str)


# ── Helpers ────────────────────────────────────────────────────────────────────

def _write(zf: zipfile.ZipFile, folder: str, filename: str, content: str) -> None:
    zf.writestr(f"{folder}/{filename}", content.encode("utf-8"))
